name: lazarus_job_tracker
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  provider: ^6.1.2 
  url_launcher: ^6.3.0
  intl: ^0.17.0
  responsive_framework: ^0.1.0  # Added for responsive design
  fluro: ^2.0.5  # Added for advanced routing
  flutter_secure_storage: ^7.0.1  # Added for secure storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Ensure linting is included

flutter:
  uses-material-design: true

  assets:
    - assets/images/
