// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJxY8PB--ivFXz8FrczX3tkMYJaOodWH0',
    appId: '1:828630352112:web:d21e155d85b2e863a14235',
    messagingSenderId: '828630352112',
    projectId: 'lazarus-d797f',
    authDomain: 'lazarus-d797f.firebaseapp.com',
    storageBucket: 'lazarus-d797f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0IctVNBtGo5lDxKrrMAwqpTLauMqn8BM',
    appId: '1:828630352112:android:7afb3c58711136c3a14235',
    messagingSenderId: '828630352112',
    projectId: 'lazarus-d797f',
    storageBucket: 'lazarus-d797f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmpDQu97XcSP1b0SuXwNDL245cW0wAcQA',
    appId: '1:828630352112:ios:49544737b3fbcabfa14235',
    messagingSenderId: '828630352112',
    projectId: 'lazarus-d797f',
    storageBucket: 'lazarus-d797f.appspot.com',
    iosBundleId: 'com.mcleodsolutions.lazarusJobTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmpDQu97XcSP1b0SuXwNDL245cW0wAcQA',
    appId: '1:828630352112:ios:49544737b3fbcabfa14235',
    messagingSenderId: '828630352112',
    projectId: 'lazarus-d797f',
    storageBucket: 'lazarus-d797f.appspot.com',
    iosBundleId: 'com.mcleodsolutions.lazarusJobTracker',
  );
}
